// Code generated by counterfeiter. DO NOT EDIT.
package servicesfake

import (
	"net/http"
	"sync"

	"github.com/xcomponent/xc-cli/services"
)

type FakeHttpService struct {
	GetStub        func(url string) (resp *http.Response, err error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		url string
	}
	getReturns struct {
		result1 *http.Response
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *http.Response
		result2 error
	}
	GetJsonStub        func(url string, target interface{}) error
	getJsonMutex       sync.RWMutex
	getJsonArgsForCall []struct {
		url    string
		target interface{}
	}
	getJsonReturns struct {
		result1 error
	}
	getJsonReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHttpService) Get(url string) (resp *http.Response, err error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		url string
	}{url})
	fake.recordInvocation("Get", []interface{}{url})
	fake.getMutex.Unlock()
	if fake.GetStub != nil {
		return fake.GetStub(url)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getReturns.result1, fake.getReturns.result2
}

func (fake *FakeHttpService) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *FakeHttpService) GetArgsForCall(i int) string {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return fake.getArgsForCall[i].url
}

func (fake *FakeHttpService) GetReturns(result1 *http.Response, result2 error) {
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *http.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeHttpService) GetReturnsOnCall(i int, result1 *http.Response, result2 error) {
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *http.Response
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *http.Response
		result2 error
	}{result1, result2}
}

func (fake *FakeHttpService) GetJson(url string, target interface{}) error {
	fake.getJsonMutex.Lock()
	ret, specificReturn := fake.getJsonReturnsOnCall[len(fake.getJsonArgsForCall)]
	fake.getJsonArgsForCall = append(fake.getJsonArgsForCall, struct {
		url    string
		target interface{}
	}{url, target})
	fake.recordInvocation("GetJson", []interface{}{url, target})
	fake.getJsonMutex.Unlock()
	if fake.GetJsonStub != nil {
		return fake.GetJsonStub(url, target)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.getJsonReturns.result1
}

func (fake *FakeHttpService) GetJsonCallCount() int {
	fake.getJsonMutex.RLock()
	defer fake.getJsonMutex.RUnlock()
	return len(fake.getJsonArgsForCall)
}

func (fake *FakeHttpService) GetJsonArgsForCall(i int) (string, interface{}) {
	fake.getJsonMutex.RLock()
	defer fake.getJsonMutex.RUnlock()
	return fake.getJsonArgsForCall[i].url, fake.getJsonArgsForCall[i].target
}

func (fake *FakeHttpService) GetJsonReturns(result1 error) {
	fake.GetJsonStub = nil
	fake.getJsonReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeHttpService) GetJsonReturnsOnCall(i int, result1 error) {
	fake.GetJsonStub = nil
	if fake.getJsonReturnsOnCall == nil {
		fake.getJsonReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.getJsonReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeHttpService) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	fake.getJsonMutex.RLock()
	defer fake.getJsonMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHttpService) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ services.HttpService = new(FakeHttpService)
